name: Github Actions for Java API Automation Project

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    env:
      # Форсируем Node.js 24 для Actions, чтобы избежать deprecation
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

    steps:
      # 1️⃣ Проверка кода
      - uses: actions/checkout@v4

      # 2️⃣ Установка Java
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 18

      # 3️⃣ Компиляция
      - name: Build
        run: mvn clean compile

      # 4️⃣ Запуск тестов (даже если упадут)
      - name: Run tests
        run: mvn test
        continue-on-error: true

      # 5️⃣ Генерация Allure отчёта в отдельную папку
      - name: Generate Allure report
        run: mvn allure:report -Dallure.results.directory=allure-results -Dallure.report.directory=allure-report

      # 6️⃣ Публикация на GitHub Pages
      - name: Deploy Allure report to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: allure-report
          publish_branch: gh-pages
          force_orphan: true       # создаёт чистую ветку без истории
          user_name: github-actions
          user_email: github-actions@github.com